import { useEffect, useMemo, useState } from 'react'
import { FiAward, FiChevronDown, FiChevronUp, FiDatabase, FiEdit3, FiExternalLink, FiLayout, FiLogIn, FiLogOut, FiMail, FiPlus, FiRefreshCw, FiSave, FiSettings, FiTrash2, FiUsers, FiX } from 'react-icons/fi'

const sections = ['socials','navLinks','stats','skills','additionalSkills','education','experience','projects','certificates']
const labels = { socials:'Social Links', navLinks:'Navigation', stats:'Stats', skills:'Skills', additionalSkills:'Other Skills', education:'Education', experience:'Experience', projects:'Projects', certificates:'Certificates' }
const icons = { settings:FiSettings, socials:FiExternalLink, navLinks:FiLayout, stats:FiAward, skills:FiDatabase, additionalSkills:FiDatabase, education:FiDatabase, experience:FiDatabase, projects:FiDatabase, certificates:FiAward, messages:FiMail, subscribers:FiUsers }
const templates = {
  socials:{name:'',url:'',icon:'github'}, navLinks:{name:'New Link',href:'#'}, stats:{label:'New Stat',value:'0',icon:'award'},
  skills:{category:'Frontend Development',name:'New Skill',level:50,icon:'react'}, additionalSkills:'New Skill',
  education:{degree:'',institution:'',duration:'',location:'',grade:'',description:'',courses:[]},
  experience:{role:'',company:'',duration:'',type:'Internship',description:'',achievements:[]},
  projects:{title:'New Project',description:'',image:'',tags:[],github:'',demo:'',featured:false},
  certificates:{title:'New Certificate',issuer:'',date:'',image:'',credentialId:'',link:'#'},
}

async function api(url, options={}) {
  const response = await fetch(url, { credentials:'include', ...options, headers:{'Content-Type':'application/json', ...(options.headers||{})} })
  const data = await response.json().catch(()=>({}))
  if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`)
  return data
}

function Button({children,className='',...props}) { return <button type="button" {...props} className={`min-h-11 rounded-xl px-3 text-sm transition focus:outline-none focus:ring-2 focus:ring-orange-400/60 disabled:cursor-not-allowed disabled:opacity-50 ${className}`}>{children}</button> }
function Input({label,value,onChange,type='text',placeholder=''}) { return <label className="block"><span className="mb-1.5 block text-xs font-medium text-slate-400">{label}</span><input type={type} value={value ?? ''} placeholder={placeholder} onChange={e=>onChange(type==='number' ? Number(e.target.value) : e.target.value)} className="min-h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 text-sm text-white outline-none transition focus:border-orange-400" /></label> }
function Textarea({label,value,onChange,rows=4,help=''}) { return <label className="block"><span className="mb-1.5 block text-xs font-medium text-slate-400">{label}</span><textarea rows={rows} value={value ?? ''} onChange={e=>onChange(e.target.value)} className="w-full resize-y rounded-xl border border-slate-700 bg-slate-900 px-3 py-3 text-sm text-white outline-none transition focus:border-orange-400" />{help&&<span className="mt-1 block text-[11px] text-slate-500">{help}</span>}</label> }
function Toggle({label,value,onChange}) { return <label className="flex min-h-11 cursor-pointer items-center justify-between gap-3 rounded-xl border border-slate-700 bg-slate-900 px-3"><span className="text-sm text-slate-300">{label}</span><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)} className="h-5 w-5 accent-orange-500" /></label> }
function FileUpload({label,value,onChange,help='PNG, JPG, WEBP or GIF • max 2 MB'}) {
  const [error,setError]=useState('')
  async function choose(e){
    const file=e.target.files?.[0]; if(!file) return
    setError('')
    if(!file.type.startsWith('image/')){setError('Please choose an image file.');e.target.value='';return}
    if(file.size>2*1024*1024){setError('Image must be 2 MB or smaller.');e.target.value='';return}
    const reader=new FileReader()
    reader.onload=()=>onChange(String(reader.result||''))
    reader.onerror=()=>setError('Could not read this image.')
    reader.readAsDataURL(file)
  }
  return <div className="space-y-2"><span className="block text-xs font-medium text-slate-400">{label}</span><div className="flex flex-col gap-3 rounded-2xl border border-dashed border-slate-700 bg-slate-950/60 p-3 sm:flex-row sm:items-center"><label className="inline-flex min-h-11 cursor-pointer items-center justify-center rounded-xl bg-slate-800 px-4 text-sm font-medium text-white hover:bg-slate-700">Choose image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={choose} className="sr-only" /></label>{value?<div className="flex min-w-0 items-center gap-3"><img src={value} alt="Selected preview" className="h-14 w-14 shrink-0 rounded-xl object-cover border border-slate-700"/><button type="button" onClick={()=>onChange('')} className="min-h-11 rounded-xl px-3 text-sm text-red-300 hover:bg-red-500/10">Remove</button></div>:<span className="text-xs text-slate-500">No image selected</span>}</div><span className="block text-[11px] text-slate-500">{help}</span>{error&&<span className="block text-xs text-red-300">{error}</span>}<Input label="Or use image URL" value={value?.startsWith('data:')?'':value} onChange={onChange} placeholder="https://…"/></div>
}
function listToText(value) { return Array.isArray(value) ? value.join('\n') : '' }
function textToList(value) { return value.split('\n').map(v=>v.trim()).filter(Boolean) }

function Login({onLogin}) {
  const [email,setEmail]=useState(''), [password,setPassword]=useState(''), [busy,setBusy]=useState(false), [error,setError]=useState('')
  async function submit(e){ e.preventDefault(); setBusy(true); setError(''); try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({email,password})});onLogin(d.user)}catch(err){setError(err.message)}finally{setBusy(false)} }
  return <div className="flex min-h-screen items-center justify-center bg-slate-950 px-4 text-white"><form onSubmit={submit} className="w-full max-w-sm rounded-3xl border border-slate-800 bg-slate-900/80 p-6 shadow-xl"><div className="mb-6 flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-500"><FiLogIn size={21}/></div><h1 className="text-2xl font-bold">Admin Portal</h1><p className="mb-6 mt-1 text-sm text-slate-400">Manage your portfolio in one simple place.</p>{error&&<div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}<div className="space-y-4"><Input label="Email" value={email} onChange={setEmail} type="email"/><Input label="Password" value={password} onChange={setPassword} type="password"/></div><button disabled={busy} className="mt-5 min-h-12 w-full rounded-xl bg-orange-500 font-semibold text-white hover:bg-orange-500">{busy?'Signing in…':'Sign in'}</button></form></div>
}

function SettingsEditor({settings,onSaved}) {
  const [form,setForm]=useState(settings), [busy,setBusy]=useState(false), [notice,setNotice]=useState('')
  useEffect(()=>setForm(settings),[settings])
  const set=(key,value)=>setForm(prev=>({...prev,[key]:value}))
  async function save(){setBusy(true);setNotice('');try{await api('/api/admin/content',{method:'PUT',body:JSON.stringify({section:'settings',data:{...form,aboutParagraphs:Array.isArray(form.aboutParagraphs)?form.aboutParagraphs:textToList(form.aboutParagraphs||'')}})});setNotice('Saved. The public site will read the new data from the database.');await onSaved()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  const aboutText=Array.isArray(form.aboutParagraphs)?form.aboutParagraphs.join('\n\n'):String(form.aboutParagraphs||'')
  return <EditorShell title="Site Settings" subtitle="Update the main text and contact details."><div className="grid gap-4 md:grid-cols-2"><Input label="Name" value={form.name} onChange={v=>set('name',v)}/><Input label="Role" value={form.role} onChange={v=>set('role',v)}/><Input label="Hero badge" value={form.heroBadge} onChange={v=>set('heroBadge',v)}/><Input label="Email" value={form.email} onChange={v=>set('email',v)}/><Input label="Phone" value={form.phone} onChange={v=>set('phone',v)}/><Input label="Location" value={form.location} onChange={v=>set('location',v)}/><Input label="Availability" value={form.availability} onChange={v=>set('availability',v)}/><Input label="Availability hours" value={form.availabilityHours} onChange={v=>set('availabilityHours',v)}/><div className="md:col-span-2"><Textarea label="Hero description" value={form.heroDescription} onChange={v=>set('heroDescription',v)} rows={3}/></div><Input label="About title" value={form.aboutTitle} onChange={v=>set('aboutTitle',v)}/><div className="md:col-span-2"><Textarea label="About paragraphs" value={aboutText} onChange={v=>set('aboutParagraphs',textToList(v.replace(/\n\s*\n/g,'\n')))} rows={6} help="Use one paragraph per line."/></div><div className="md:col-span-2"><Textarea label="Contact heading" value={form.contactHeading} onChange={v=>set('contactHeading',v)} rows={2}/></div><div className="md:col-span-2"><Textarea label="Contact description" value={form.contactDescription} onChange={v=>set('contactDescription',v)} rows={3}/></div><div className="md:col-span-2"><Textarea label="Contact intro" value={form.contactIntro} onChange={v=>set('contactIntro',v)} rows={3}/></div><div className="md:col-span-2"><Textarea label="Footer bio" value={form.footerBio} onChange={v=>set('footerBio',v)} rows={3}/></div><Input label="Footer copyright" value={form.footerCopyright} onChange={v=>set('footerCopyright',v)}/><div className="md:col-span-2 grid gap-4 md:grid-cols-2"><FileUpload label="Profile image 1" value={form.profileImage1} onChange={v=>set('profileImage1',v)}/><FileUpload label="Profile image 2" value={form.profileImage2} onChange={v=>set('profileImage2',v)}/></div></div><SaveBar busy={busy} notice={notice} onSave={save}/></EditorShell>
}

function Fields({section,value,setValue}) {
  const set=(k,v)=>setValue({...value,[k]:v})
  if(section==='additionalSkills') return <Textarea label="Skill" value={value} onChange={v=>setValue(v)} rows={2}/>
  if(section==='socials') return <div className="grid gap-4 md:grid-cols-2"><Input label="Name" value={value.name} onChange={v=>set('name',v)}/><Input label="URL" value={value.url} onChange={v=>set('url',v)}/><Input label="Icon" value={value.icon} onChange={v=>set('icon',v)}/></div>
  if(section==='navLinks') return <div className="grid gap-4 md:grid-cols-2"><Input label="Name" value={value.name} onChange={v=>set('name',v)}/><Input label="Link / href" value={value.href} onChange={v=>set('href',v)}/></div>
  if(section==='stats') return <div className="grid gap-4 md:grid-cols-3"><Input label="Label" value={value.label} onChange={v=>set('label',v)}/><Input label="Value" value={value.value} onChange={v=>set('value',v)}/><Input label="Icon" value={value.icon} onChange={v=>set('icon',v)}/></div>
  if(section==='skills') return <div className="grid gap-4 md:grid-cols-2"><Input label="Category" value={value.category} onChange={v=>set('category',v)}/><Input label="Skill name" value={value.name} onChange={v=>set('name',v)}/><Input label="Level (0–100)" type="number" value={value.level} onChange={v=>set('level',Math.max(0,Math.min(100,v||0)))}/><Input label="Icon" value={value.icon} onChange={v=>set('icon',v)}/></div>
  if(section==='education') return <div className="grid gap-4 md:grid-cols-2"><Input label="Degree" value={value.degree} onChange={v=>set('degree',v)}/><Input label="Institution" value={value.institution} onChange={v=>set('institution',v)}/><Input label="Duration" value={value.duration} onChange={v=>set('duration',v)}/><Input label="Location" value={value.location} onChange={v=>set('location',v)}/><Input label="Grade" value={value.grade} onChange={v=>set('grade',v)}/><div className="md:col-span-2"><Textarea label="Description" value={value.description} onChange={v=>set('description',v)} rows={3}/></div><div className="md:col-span-2"><Textarea label="Courses" value={listToText(value.courses)} onChange={v=>set('courses',textToList(v))} help="One course per line."/></div></div>
  if(section==='experience') return <div className="grid gap-4 md:grid-cols-2"><Input label="Role" value={value.role} onChange={v=>set('role',v)}/><Input label="Company" value={value.company} onChange={v=>set('company',v)}/><Input label="Duration" value={value.duration} onChange={v=>set('duration',v)}/><Input label="Type" value={value.type} onChange={v=>set('type',v)}/><div className="md:col-span-2"><Textarea label="Description" value={value.description} onChange={v=>set('description',v)} rows={3}/></div><div className="md:col-span-2"><Textarea label="Achievements" value={listToText(value.achievements)} onChange={v=>set('achievements',textToList(v))} help="One achievement per line."/></div></div>
  if(section==='projects') return <div className="grid gap-4 md:grid-cols-2"><Input label="Title" value={value.title} onChange={v=>set('title',v)}/><FileUpload label="Project image" value={value.image} onChange={v=>set('image',v)}/><div className="md:col-span-2"><Textarea label="Description" value={value.description} onChange={v=>set('description',v)} rows={3}/></div><Textarea label="Tags" value={listToText(value.tags)} onChange={v=>set('tags',textToList(v))} help="One tag per line."/><div className="space-y-4"><Input label="GitHub URL" value={value.github} onChange={v=>set('github',v)}/><Input label="Demo URL" value={value.demo} onChange={v=>set('demo',v)}/><Toggle label="Featured project" value={value.featured} onChange={v=>set('featured',v)}/></div></div>
  if(section==='certificates') return <div className="grid gap-4 md:grid-cols-2"><Input label="Title" value={value.title} onChange={v=>set('title',v)}/><Input label="Issuer" value={value.issuer} onChange={v=>set('issuer',v)}/><Input label="Date" value={value.date} onChange={v=>set('date',v)}/><Input label="Credential ID" value={value.credentialId} onChange={v=>set('credentialId',v)}/><FileUpload label="Certificate image" value={value.image} onChange={v=>set('image',v)}/><Input label="Certificate URL" value={value.link} onChange={v=>set('link',v)}/></div>
  return null
}

function SaveBar({busy,notice,onSave,onCancel}) { return <div className="mt-6 flex flex-wrap items-center gap-3 border-t border-slate-800 pt-4"><Button onClick={onSave} disabled={busy} className="bg-orange-500 px-5 font-semibold text-white hover:bg-orange-500"><FiSave className="mr-2 inline"/>{busy?'Saving…':'Save changes'}</Button>{onCancel&&<Button onClick={onCancel} className="bg-slate-800 text-slate-300">Cancel</Button>}{notice&&<span className="text-sm text-slate-400">{notice}</span>}</div> }
function EditorShell({title,subtitle,children}) { return <section><div className="mb-6"><h2 className="text-2xl font-bold text-white">{title}</h2><p className="mt-1 text-sm text-slate-400">{subtitle}</p></div>{children}</section> }

function SectionEditor({section,items,onRefresh}) {
  const [editing,setEditing]=useState(null), [draft,setDraft]=useState(null), [busy,setBusy]=useState(false), [notice,setNotice]=useState('')
  const begin=(item)=>{setEditing(item.id);setDraft(item.value!==undefined?item.value:{...item});setNotice('')}
  const save=async()=>{setBusy(true);setNotice('');try{await api('/api/admin/content',{method:'PATCH',body:JSON.stringify({section,id:editing,data:draft})});setEditing(null);setDraft(null);setNotice('Saved successfully.');await onRefresh()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  const add=async()=>{setBusy(true);setNotice('');try{await api('/api/admin/content',{method:'POST',body:JSON.stringify({section,data:templates[section],position:items.length})});setNotice('Added successfully.');await onRefresh()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  const remove=async(id)=>{if(!window.confirm('Delete this item?'))return;setBusy(true);try{await api('/api/admin/content',{method:'DELETE',body:JSON.stringify({section,id})});await onRefresh()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  const move=async(index,dir)=>{const other=index+dir;if(other<0||other>=items.length)return;setBusy(true);try{await Promise.all([api('/api/admin/content',{method:'PATCH',body:JSON.stringify({section,id:items[index].id,data:items[index].value!==undefined?items[index].value:items[index],position:other})}),api('/api/admin/content',{method:'PATCH',body:JSON.stringify({section,id:items[other].id,data:items[other].value!==undefined?items[other].value:items[other],position:index})})]);await onRefresh()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  return <EditorShell title={labels[section]} subtitle="Add, edit, reorder or remove content. Every save is persisted in PostgreSQL."><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-500">{items.length} {items.length===1?'item':'items'}</span><Button onClick={add} disabled={busy} className="bg-orange-500 text-white hover:bg-orange-500"><FiPlus className="mr-2 inline"/>Add {section==='additionalSkills'?'skill':'item'}</Button></div>{notice&&<div className="mb-4 rounded-xl border border-slate-800 bg-slate-900 p-3 text-sm text-slate-300">{notice}</div>}<div className="space-y-3">{items.map((item,index)=><div key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex gap-3"><div className="flex shrink-0 flex-col gap-1"><Button aria-label="Move up" onClick={()=>move(index,-1)} disabled={busy||index===0} className="w-10 bg-slate-800 text-slate-400"><FiChevronUp/></Button><Button aria-label="Move down" onClick={()=>move(index,1)} disabled={busy||index===items.length-1} className="w-10 bg-slate-800 text-slate-400"><FiChevronDown/></Button></div><div className="min-w-0 flex-1">{editing===item.id?<><Fields section={section} value={draft} setValue={setDraft}/><SaveBar busy={busy} notice={notice} onSave={save} onCancel={()=>{setEditing(null);setDraft(null)}}/></>:<div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="font-medium text-white">{getItemTitle(section,item)}</p><p className="mt-1 break-words text-xs text-slate-500">{getItemSummary(section,item)}</p></div><div className="flex shrink-0 gap-2"><Button onClick={()=>begin(item)} className="bg-slate-800 text-slate-200"><FiEdit3 className="mr-2 inline"/>Edit</Button><Button onClick={()=>remove(item.id)} disabled={busy} className="bg-red-500/10 text-red-300"><FiTrash2/></Button></div></div>}</div></div></div>)}</div>{items.length===0&&<div className="rounded-2xl border border-dashed border-slate-800 p-10 text-center text-sm text-slate-500">Nothing here yet. Add your first item.</div>}</EditorShell>
}
function getItemTitle(section,item){if(section==='additionalSkills')return item.value||item||'Skill';return item.name||item.title||item.role||item.degree||item.label||'Untitled item'}
function getItemSummary(section,item){if(section==='additionalSkills')return 'Additional skill';return item.company||item.institution||item.issuer||item.url||item.href||item.description||'Ready to edit'}

function DataView({title,rows,type,onRefresh}) { const [busy,setBusy]=useState(false); async function remove(id){if(!window.confirm('Delete this record?'))return;setBusy(true);try{await api(`/api/admin/${type}`,{method:'DELETE',body:JSON.stringify({id})});await onRefresh()}finally{setBusy(false)}} return <EditorShell title={title} subtitle={`${rows.length} records stored in the database.`}><div className="space-y-3">{rows.map(row=><div key={row.id} className="flex flex-col gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="break-words font-medium text-white">{row.name||row.email||row.subject||'Record'}</p><p className="break-words text-xs text-slate-500">{row.email||row.created_at}</p>{type==='messages'&&<p className="mt-2 whitespace-pre-wrap break-words text-sm text-slate-300">{row.message}</p>}</div><Button disabled={busy} onClick={()=>remove(row.id)} className="bg-red-500/10 text-red-300 sm:w-auto"><FiTrash2 className="mr-2 inline"/>Delete</Button></div>)}</div>{rows.length===0&&<div className="rounded-2xl border border-dashed border-slate-800 p-10 text-center text-sm text-slate-500">No records yet.</div>}</EditorShell> }

function Dashboard({user,onLogout}) {
  const [tab,setTab]=useState('settings'), [settings,setSettings]=useState({}), [items,setItems]=useState({}), [messages,setMessages]=useState([]), [subscribers,setSubscribers]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('')
  async function load(){setLoading(true);setError('');try{const [content,m,s]=await Promise.all([api('/api/admin/content'),api('/api/admin/messages'),api('/api/admin/subscribers')]);setSettings(content.settings||{});const grouped={};for(const row of content.items||[])(grouped[row.section]??=[]).push({id:row.id,...(row.data&&typeof row.data==='object'&&!Array.isArray(row.data)?row.data:{value:row.data})});setItems(grouped);setMessages(m);setSubscribers(s)}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const nav=useMemo(()=>[['settings','Site Settings'],...sections.map(s=>[s,labels[s]]),['messages','Messages'],['subscribers','Subscribers']],[])
  if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-950 text-sm text-slate-500">Loading admin data…</div>
  return <div className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-950/95"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-4 sm:px-6"><div><h1 className="text-lg font-bold">Portfolio Admin</h1><p className="text-xs text-slate-500">{user.email}</p></div><div className="flex gap-2"><a href="/" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-3 text-sm text-slate-300"><FiExternalLink/>Site</a><Button onClick={load} aria-label="Refresh" className="bg-slate-900 text-slate-300"><FiRefreshCw/></Button><Button onClick={onLogout} className="bg-slate-900 text-slate-300"><FiLogOut/></Button></div></div></header><div className="mx-auto max-w-7xl px-4 py-4 sm:px-6 sm:py-6"><div className="mb-4 lg:hidden"><select value={tab} onChange={e=>setTab(e.target.value)} className="min-h-12 w-full rounded-xl border border-slate-800 bg-slate-900 px-3 text-white outline-none">{nav.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div><div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="hidden h-fit rounded-2xl border border-slate-800 bg-slate-900/50 p-2 lg:block">{nav.map(([id,label])=>{const Icon=icons[id]||FiDatabase;return <button key={id} type="button" onClick={()=>setTab(id)} className={`mb-1 flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-sm transition ${tab===id?'bg-orange-500 text-white':'text-slate-400 hover:bg-slate-800 hover:text-white'}`}><Icon/>{label}</button>})}</aside><main className="min-w-0 rounded-2xl border border-slate-800 bg-slate-900/30 p-4 sm:p-6">{error?<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}<Button onClick={load} className="ml-2 bg-slate-800">Retry</Button></div>:tab==='settings'?<SettingsEditor settings={settings} onSaved={load}/>:tab==='messages'?<DataView title="Messages" rows={messages} type="messages" onRefresh={load}/>:tab==='subscribers'?<DataView title="Subscribers" rows={subscribers} type="subscribers" onRefresh={load}/>:<SectionEditor section={tab} items={items[tab]||[]} onRefresh={load}/>}</main></div></div></div>
}

export default function AdminApp(){const [user,setUser]=useState(null),[checking,setChecking]=useState(true);useEffect(()=>{api('/api/admin/me').then(d=>setUser(d.user)).catch(()=>{}).finally(()=>setChecking(false))},[]);if(checking)return <div className="flex min-h-screen items-center justify-center bg-slate-950 text-sm text-slate-500">Checking authentication…</div>;if(!user)return <Login onLogin={setUser}/>;return <Dashboard user={user} onLogout={async()=>{await api('/api/admin/logout',{method:'POST'});setUser(null)}}/>}
